# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-memorystore
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    source:
      repo: https://github.com/terraform-google-modules/terraform-google-memorystore.git
      sourceType: git
    version: 10.0.0
    actuationTool:
      flavor: Terraform
      version: ">= 0.13"
    description: {}
  content:
    subBlueprints:
      - name: memcache
        location: modules/memcache
      - name: redis-cluster
        location: modules/redis-cluster
    examples:
      - name: basic
        location: examples/basic
      - name: memcache
        location: examples/memcache
      - name: minimal
        location: examples/minimal
      - name: redis
        location: examples/redis
      - name: redis-cluster
        location: examples/redis-cluster
  interfaces:
    variables:
      - name: alternative_location_id
        description: The alternative zone where the instance will be provisioned.
        varType: string
      - name: auth_enabled
        description: Indicates whether OSS Redis AUTH is enabled for the instance. If set to true AUTH is enabled on the instance.
        varType: bool
        defaultValue: false
      - name: authorized_network
        description: The full name of the Google Compute Engine network to which the instance is connected. If left unspecified, the default network will be used.
        varType: string
      - name: connect_mode
        description: The connection mode of the Redis instance. Can be either DIRECT_PEERING or PRIVATE_SERVICE_ACCESS. The default connect mode if not provided is DIRECT_PEERING.
        varType: string
      - name: customer_managed_key
        description: Default encryption key to apply to the Redis instance. Defaults to null (Google-managed).
        varType: string
      - name: display_name
        description: An arbitrary and optional user-provided name for the instance.
        varType: string
      - name: enable_apis
        description: Flag for enabling redis.googleapis.com in your project
        varType: bool
        defaultValue: true
      - name: labels
        description: The resource labels to represent user provided metadata.
        varType: map(string)
      - name: location_id
        description: The zone where the instance will be provisioned. If not provided, the service will choose a zone for the instance. For STANDARD_HA tier, instances will be created across two zones for protection against zonal failures. If [alternativeLocationId] is also provided, it must be different from [locationId].
        varType: string
      - name: maintenance_policy
        description: The maintenance policy for an instance.
        varType: |-
          object({
              day = string
              start_time = object({
                hours   = number
                minutes = number
                seconds = number
                nanos   = number
              })
            })
      - name: memory_size_gb
        description: Redis memory size in GiB. Defaulted to 1 GiB
        varType: number
        defaultValue: 1
      - name: name
        description: The ID of the instance or a fully qualified identifier for the instance.
        varType: string
        required: true
      - name: persistence_config
        description: The Redis persistence configuration parameters. https://cloud.google.com/memorystore/docs/redis/reference/rest/v1/projects.locations.instances#persistenceconfig
        varType: |-
          object({
              persistence_mode    = string
              rdb_snapshot_period = string
            })
      - name: project
        description: The ID of the project in which the resource belongs to.
        varType: string
        required: true
      - name: read_replicas_mode
        description: "Read replicas mode. https://cloud.google.com/memorystore/docs/redis/reference/rest/v1/projects.locations.instances#readreplicasmode "
        varType: string
        defaultValue: READ_REPLICAS_DISABLED
      - name: redis_configs
        description: The Redis configuration parameters. See [more details](https://cloud.google.com/memorystore/docs/redis/reference/rest/v1/projects.locations.instances#Instance.FIELDS.redis_configs)
        varType: map(any)
        defaultValue: {}
      - name: redis_version
        description: The version of Redis software.
        varType: string
      - name: region
        description: The GCP region to use.
        varType: string
      - name: replica_count
        description: The number of replicas. can
        varType: number
      - name: reserved_ip_range
        description: The CIDR range of internal addresses that are reserved for this instance.
        varType: string
      - name: secondary_ip_range
        description: Optional. Additional IP range for node placement. Required when enabling read replicas on an existing instance.
        varType: string
      - name: tier
        description: The service tier of the instance. https://cloud.google.com/memorystore/docs/redis/reference/rest/v1/projects.locations.instances#Tier
        varType: string
        defaultValue: STANDARD_HA
      - name: transit_encryption_mode
        description: The TLS mode of the Redis instance, If not provided, TLS is enabled for the instance.
        varType: string
        defaultValue: SERVER_AUTHENTICATION
    outputs:
      - name: auth_string
        description: AUTH String set on the instance. This field will only be populated if auth_enabled is true.
      - name: current_location_id
        description: The current zone where the Redis endpoint is placed.
      - name: env_vars
        description: Exported environment variables
      - name: host
        description: The IP address of the instance.
      - name: id
        description: The memorystore instance ID.
      - name: persistence_iam_identity
        description: Cloud IAM identity used by import/export operations. Format is 'serviceAccount:'. May change over time
      - name: port
        description: The port number of the exposed Redis endpoint.
      - name: read_endpoint
        description: " The IP address of the exposed readonly Redis endpoint."
      - name: region
        description: The region the instance lives in.
      - name: server_ca_certs
        description: List of server CA certificates for the instance
  requirements:
    roles:
      - level: Project
        roles:
          - roles/owner
    services:
      - cloudresourcemanager.googleapis.com
      - serviceusage.googleapis.com
      - redis.googleapis.com
      - memcache.googleapis.com
      - serviceconsumermanagement.googleapis.com
      - networkconnectivity.googleapis.com
      - compute.googleapis.com
