# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-memorystore
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: Memorystore Redis Cluster Terraform Module
    source:
      repo: https://github.com/terraform-google-modules/terraform-google-memorystore.git
      sourceType: git
      dir: /modules/redis-cluster
    version: 15.1.0
    actuationTool:
      flavor: Terraform
      version: ">= 1.3"
    description: {}
  content:
    examples:
      - name: basic
        location: examples/basic
      - name: memcache
        location: examples/memcache
      - name: minimal
        location: examples/minimal
      - name: redis
        location: examples/redis
      - name: redis-cluster
        location: examples/redis-cluster
      - name: valkey
        location: examples/valkey
  interfaces:
    variables:
      - name: name
        description: The ID of the instance or a fully qualified identifier for the instance. must be 1 to 63 characters and use only lowercase letters, numbers, or hyphens. It must start with a lowercase letter and end with a lowercase letter or number
        varType: string
        required: true
      - name: project_id
        description: The ID of the project in which the resource belongs to.
        varType: string
        required: true
      - name: region
        description: The name of the region of the Redis cluster
        varType: string
        required: true
      - name: enable_apis
        description: Flag for enabling memcache.googleapis.com in your project
        varType: bool
        defaultValue: true
      - name: shard_count
        description: Required. Number of shards for the Redis cluster. The minimum number of shards in a Memorystore cluster is 3 shards
        varType: number
        defaultValue: 3
      - name: replica_count
        description: The number of replica nodes per shard. Each shard can have 0, 1, or 2 replica nodes. Replicas provide high availability and additional read throughput, and are evenly distributed across zones
        varType: number
        defaultValue: 0
      - name: transit_encryption_mode
        description: "The in-transit encryption for the Redis cluster. If not provided, encryption is disabled for the cluster. Default value is TRANSIT_ENCRYPTION_MODE_DISABLED. Possible values are: TRANSIT_ENCRYPTION_MODE_UNSPECIFIED, TRANSIT_ENCRYPTION_MODE_DISABLED, TRANSIT_ENCRYPTION_MODE_SERVER_AUTHENTICATION"
        varType: string
        defaultValue: TRANSIT_ENCRYPTION_MODE_DISABLED
      - name: authorization_mode
        description: "The authorization mode of the Redis cluster. If not provided, auth feature is disabled for the cluster. Default value is AUTH_MODE_DISABLED. Possible values are: AUTH_MODE_UNSPECIFIED, AUTH_MODE_IAM_AUTH, AUTH_MODE_DISABLED"
        varType: string
        defaultValue: AUTH_MODE_DISABLED
      - name: network
        description: List of consumer network where the network address of the discovery endpoint will be reserved, in the form of projects/{network_project_id_or_number}/global/networks/{network_id}. Currently, only one item is supported
        varType: list(string)
        required: true
        connections:
          - source:
              source: github.com/terraform-google-modules/terraform-google-network//modules/vpc
              version: ">= 9.1.0"
            spec:
              outputExpr: network_id
      - name: service_connection_policies
        description: The Service Connection Policies to create
        varType: |-
          map(object({
              description     = optional(string)
              network_name    = string
              network_project = string
              subnet_names    = list(string)
              limit           = optional(number)
              labels          = optional(map(string), {})
            }))
        defaultValue: {}
      - name: node_type
        description: "The nodeType for the Redis cluster. If not provided, REDIS_HIGHMEM_MEDIUM will be used as default Possible values are: REDIS_SHARED_CORE_NANO, REDIS_HIGHMEM_MEDIUM, REDIS_HIGHMEM_XLARGE, REDIS_STANDARD_SMALL."
        varType: string
      - name: redis_configs
        description: Configure Redis Cluster behavior using a subset of native Redis configuration parameters
        varType: |-
          object({
              maxmemory-clients       = optional(string)
              maxmemory               = optional(string)
              maxmemory-policy        = optional(string)
              notify-keyspace-events  = optional(string)
              slowlog-log-slower-than = optional(number)
              maxclients              = optional(number)
            })
      - name: zone_distribution_config_mode
        description: "The mode for zone distribution for Memorystore Redis cluster (Immutable). If not provided, MULTI_ZONE will be used as default value. Possible values are: MULTI_ZONE, SINGLE_ZONE"
        varType: string
        defaultValue: MULTI_ZONE
      - name: zone_distribution_config_zone
        description: The zone for single zone Memorystore Redis cluster (Immutable)
        varType: string
      - name: deletion_protection_enabled
        description: " Indicates if the cluster is deletion protected or not. If the value if set to true, any delete cluster operation will fail. Default value is true"
        varType: bool
        defaultValue: true
      - name: kms_key
        description: The KMS key used to encrypt the at-rest data of the cluster
        varType: string
      - name: weekly_maintenance_window
        description: Configure Redis Cluster behavior using a subset of native Redis configuration parameters
        varType: |-
          object({
              day_of_the_week = optional(string, "DAY_OF_WEEK_UNSPECIFIED")
              hours           = optional(string)
              minutes         = optional(string)
              seconds         = optional(string)
              nanos           = optional(number)
            })
      - name: persistence_config
        description: Persistence config (RDB, AOF) for the cluster
        varType: |-
          object({
              mode = optional(string, "PERSISTENCE_MODE_UNSPECIFIED")
              rdb_config = optional(object({
                rdb_snapshot_period     = optional(string)
                rdb_snapshot_start_time = optional(string)
              }), null)
              aof_config = optional(object({
                append_fsync = optional(string)
              }))
            })
      - name: cluster_role
        description: "The role of the cluster in cross cluster replication. Possible values are: CLUSTER_ROLE_UNSPECIFIED, NONE, PRIMARY, SECONDARY"
        varType: string
      - name: primary_cluster
        description: "primary cluster that is used as the replication source for this secondary cluster. This is allowed to be set only for clusters whose cluster role is of type SECONDARY. Format: projects/{project}/locations/{region}/clusters/{cluster-id}"
        varType: string
      - name: secondary_clusters
        description: "List of secondary clusters that are replicating from this primary cluster. This is allowed to be set only for clusters whose cluster role is of type PRIMARY. Format: projects/{project}/locations/{region}/clusters/{cluster-id}"
        varType: list(string)
        defaultValue: []
    outputs:
      - name: apphub_service_uri
        description: Service URI in CAIS style to be used by Apphub.
        type:
          - object
          - location: string
            service_id: string
            service_uri: string
      - name: discovery_endpoints
        description: Endpoints created on each given network, for Redis clients to connect to the cluster. Currently only one endpoint is supported
        type:
          - list
          - - object
            - address: string
              port: number
              psc_config:
                - list
                - - object
                  - network: string
      - name: env_vars
        description: Environment variables for Redis cluster connection, including address and port.
        type:
          - object
          - REDIS_CLUSTER_HOST: string
            REDIS_CLUSTER_PORT: string
      - name: id
        description: The redis cluster instance ID
        type: string
      - name: psc_connections
        description: PSC connections for discovery of the cluster topology and accessing the cluster
        type:
          - list
          - - object
            - address: string
              forwarding_rule: string
              network: string
              project_id: string
              psc_connection_id: string
      - name: psc_service_attachments
        description: The PSC service attachments of the cluster
        type:
          - list
          - - object
            - connection_type: string
              service_attachment: string
      - name: redis_cluster
        description: The redis cluster created
        type:
          - object
          - authorization_mode: string
            automated_backup_config:
              - list
              - - object
                - fixed_frequency_schedule:
                    - list
                    - - object
                      - start_time:
                          - list
                          - - object
                            - hours: number
                  retention: string
            backup_collection: string
            create_time: string
            cross_cluster_replication_config:
              - list
              - - object
                - cluster_role: string
                  membership:
                    - list
                    - - object
                      - primary_cluster:
                          - list
                          - - object
                            - cluster: string
                              uid: string
                        secondary_clusters:
                          - list
                          - - object
                            - cluster: string
                              uid: string
                  primary_cluster:
                    - list
                    - - object
                      - cluster: string
                        uid: string
                  secondary_clusters:
                    - list
                    - - object
                      - cluster: string
                        uid: string
                  update_time: string
            deletion_protection_enabled: bool
            discovery_endpoints:
              - list
              - - object
                - address: string
                  port: number
                  psc_config:
                    - list
                    - - object
                      - network: string
            gcs_source:
              - list
              - - object
                - uris:
                    - set
                    - string
            id: string
            kms_key: string
            maintenance_policy:
              - list
              - - object
                - create_time: string
                  update_time: string
                  weekly_maintenance_window:
                    - list
                    - - object
                      - day: string
                        duration: string
                        start_time:
                          - list
                          - - object
                            - hours: number
                              minutes: number
                              nanos: number
                              seconds: number
            maintenance_schedule:
              - list
              - - object
                - end_time: string
                  schedule_deadline_time: string
                  start_time: string
            managed_backup_source:
              - list
              - - object
                - backup: string
            name: string
            node_type: string
            persistence_config:
              - list
              - - object
                - aof_config:
                    - list
                    - - object
                      - append_fsync: string
                  mode: string
                  rdb_config:
                    - list
                    - - object
                      - rdb_snapshot_period: string
                        rdb_snapshot_start_time: string
            precise_size_gb: number
            project: string
            psc_configs:
              - list
              - - object
                - network: string
            psc_connections:
              - list
              - - object
                - address: string
                  forwarding_rule: string
                  network: string
                  project_id: string
                  psc_connection_id: string
            psc_service_attachments:
              - list
              - - object
                - connection_type: string
                  service_attachment: string
            redis_configs:
              - map
              - string
            region: string
            replica_count: number
            shard_count: number
            size_gb: number
            state: string
            state_info:
              - list
              - - object
                - update_info:
                    - list
                    - - object
                      - target_replica_count: number
                        target_shard_count: number
            timeouts:
              - object
              - create: string
                delete: string
                update: string
            transit_encryption_mode: string
            uid: string
            zone_distribution_config:
              - list
              - - object
                - mode: string
                  zone: string
  requirements:
    roles:
      - level: Project
        roles:
          - roles/redis.admin
          - roles/iam.serviceAccountUser
          - roles/logging.logWriter
          - roles/cloudkms.cryptoKeyEncrypterDecrypter
    services:
      - cloudkms.googleapis.com
      - redis.googleapis.com
      - serviceusage.googleapis.com
    providerVersions:
      - source: hashicorp/google
        version: ">= 6.22, < 7"
